# Generated by Django 5.2 on 2025-06-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('clima', models.CharField(choices=[('templado', 'Templado'), ('tropical', 'Tropical')], max_length=10)),
                ('poblacion', models.IntegerField()),
                ('foto', models.ImageField(upload_to='inform')),
                ('folleto', models.FileField(upload_to='inform')),
            ],
        ),
    ]
