# Generated by Django 5.2 on 2025-06-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ciudad', '0002_alter_ciudad_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='folleto',
            field=models.FileField(blank=True, null=True, upload_to='inform'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='inform'),
        ),
    ]
