# Generated by Django 5.2 on 2025-06-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ciudad', '0005_alter_ciudad_folleto_alter_ciudad_foto'),
        ('Lugares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='lugares',
            field=models.ManyToManyField(blank=True, null=True, to='Lugares.lugares'),
        ),
    ]
