# Generated by Django 5.2 on 2025-06-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lugares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('resena', models.TextField()),
                ('horario', models.FileField(upload_to='lugares')),
                ('historia', models.FileField(upload_to='lugares')),
            ],
        ),
    ]
